- name: Garantir label da partição root (btrfs)
  ansible.builtin.command: "btrfs filesystem label {{ particoes.root.device }} {{ particoes.root.label }}"
  when:
    - particoes.root.formato == 'btrfs'
    - particoes.root.device is defined and particoes.root.device | length > 0
    - particoes.root.label is defined and particoes.root.label | length > 0
  changed_when: false
  become: true

- name: Garantir label da partição root (ext4)
  ansible.builtin.command: "e2label {{ particoes.root.device }} {{ particoes.root.label }}"
  when:
    - particoes.root.formato == 'ext4'
    - particoes.root.device is defined and particoes.root.device | length > 0
    - particoes.root.label is defined and particoes.root.label | length > 0
  changed_when: false
  become: true

- name: Garantir label da partição home
  ansible.builtin.command: "e2label {{ particoes.home.device }} {{ particoes.home.label }}"
  when:
    - particoes.home.device is defined and particoes.home.device | length > 0
    - particoes.home.label is defined and particoes.home.label | length > 0
  changed_when: false
  become: true

- name: Garantir label da partição boot
  ansible.builtin.command: "fatlabel {{ particoes.boot.device }} {{ particoes.boot.label }}"
  when:
    - particoes.boot.device is defined and particoes.boot.device | length > 0
    - particoes.boot.label is defined and particoes.boot.label | length > 0
  changed_when: false
  become: true

- name: Garantir label da partição swap
  ansible.builtin.command: "swaplabel -L {{ particoes.swap.label }} {{ particoes.swap.device }}"
  when:
    - particoes.swap.device is defined and particoes.swap.device | length > 0
    - particoes.swap.label is defined and particoes.swap.label | length > 0
  changed_when: false
  become: true

- name: Gerar fstab
  ansible.builtin.command:
    # Executado dentro do chroot, então o ponto de montagem é /
    cmd: genfstab -L /
  register: fstab_content
  changed_when: false
  become: true

- name: Escrever /etc/fstab com base no conteúdo gerado
  become: true
  ansible.builtin.copy:
    content: "{{ fstab_content.stdout }}"
    dest: /etc/fstab

