- name: Configure repositories from plugin list
  ansible.builtin.include_tasks:
    file: process_repo.yml
  loop: "{{ repos }}"
  loop_control:
    loop_var: repo_item

- name: Ensure pacman cache is up to date
  community.general.pacman:
    update_cache: true
  become: true
