- name: Manage standard Arch Linux repositories
  when: final_repos.managed is defined and ansible_os_family == 'Archlinux'
  block:
    - name: "Manage 'core' repository state"
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR core"
        block: |
          [core]
          Include = /etc/pacman.d/mirrorlist
        state: "{{ 'present' if final_repos.managed.core | default(false) else 'absent' }}"

    - name: "Manage 'extra' repository state"
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR extra"
        block: |
          [extra]
          Include = /etc/pacman.d/mirrorlist
        state: "{{ 'present' if final_repos.managed.extras | default(false) else 'absent' }}"

    - name: "Manage 'multilib' repository state"
      ansible.builtin.blockinfile:
        path: /etc/pacman.conf
        marker: "# {mark} ANSIBLE MANAGED BLOCK FOR multilib"
        block: |
          [multilib]
          Include = /etc/pacman.d/mirrorlist
        state: "{{ 'present' if final_repos.managed.extras | default(false) else 'absent' }}"

- name: Manage third-party repositories installation
  ansible.builtin.include_tasks: process_repo.yml
  loop: "{{ final_repos.third_party | default([]) }}"
  loop_control:
    loop_var: repo_item
  when:
    - ansible_os_family == 'Archlinux'



- name: Ensure pacman cache is up to date
  community.general.pacman:
    update_cache: true
  become: true