- name: "Process third-party repo [{{ repo_item.name }}] for Arch Linux"
  when: repo_item.distribution is defined and repo_item.distribution == 'arch'
  block:
    - name: "Install CachyOS repository"
      ansible.builtin.shell: "set -e && curl -L {{ repo_item.url }} | tar xJ -C /tmp && /tmp/cachyos-repo/cachyos-repo.sh"
      args:
        creates: /etc/pacman.d/cachyos-mirrorlist
      when:
        - repo_item.name == 'cachyOS'
        - repo_item.url is defined
        - repo_item.url != ''

    - name: "Install yay aur helper"
      ansible.builtin.shell: "set -e && git clone {{ repo_item.url }}; cd yay; makepkg -si; cd ..; rm -rf yay/"
      args:
        creates: /usr/bin/yay
      when:
        - repo_item.name == 'yay'
        - repo_item.url is defined
        - repo_item.url != ''
