- name: Define base pkg list
  ansible.builtin.set_fact:
    sistema_pacotes_base: "{{ (necessarios + bootloader) | unique | list }}"

- name: (Debug) Show base pkg list
  ansible.builtin.debug:
    var: sistema_pacotes_base

- name: Install base pkgs (no chroot)
  ansible.builtin.command:
    cmd: >
      pacstrap -K /mnt --needed {{ sistema_pacotes_base | join(' ') }}
  async: 3600
  poll: 15
  changed_when: false
  when: sistema_pacotes_base is defined and sistema_pacotes_base | length > 0
