- name: Load firmware mode
  ansible.builtin.include_vars: "{{ item }}"
  loop:
    - "../vars/{{ firmware | default('UEFI') }}.yml"

- name: Define base pkg list
  ansible.builtin.set_fact:
    pacotes_base: "{{ (necessarios + bootloader) | unique | list }}"

- name: (Debug) Show base pkg list
  ansible.builtin.debug:
    var: pacotes_base

- name: Install base pkgs (no chroot)
  ansible.builtin.command:
    cmd: >
      pacstrap -K {{ fsroot }} --needed
      {% for pkg in pacotes_base %}
        {{ pkg | quote }}
      {% endfor %}
  async: 3600
  poll: 15
  changed_when: false
  when: pacotes_base is defined and pacotes_base | length > 0
