- name: Loading vars
  ansible.builtin.include_vars: "{{ plugin }}"

- name: Making sure necessary packages are installed
  community.general.pacman:
    name:
      - git
      - stow
    state: present
  become: true

- name: Iterar e processar cada dotfile da lista
  ansible.builtin.include_tasks: tasks/process_dotfile.yml
  loop: "{{ dotfiles }}"
  loop_control:
    loop_var: dotfile_item
