
- name: Carregar variáveis de Dotfiles
  ansible.builtin.include_vars: "{{ plugin }}"

- name: Garantir que os pacotes de gerenciamento estejam instalados
  ansible.builtin.pacman:
    name:
      - git
      - stow
    state: present
  become: yes

- name: Iterar e processar cada dotfile da lista
  ansible.builtin.include_tasks: tasks/process_dotfile.yml
  loop: "{{ dotfiles }}"
  loop_control:
    loop_var: dotfile_item

