- name: Making sure necessary packages are installed
  community.general.pacman:
    name:
      - git
      - stow
    state: present
  become: true

- name: Iterate through dotfiles list
  ansible.builtin.include_tasks: tasks/process_dotfile.yml
  loop: "{{ dotfiles }}"
  loop_control:
    loop_var: dotfile_item
