- name: "Manage dotfile based on 'open' flag"
  block:
    # This block handles the case where we symlink the contents of a directory
    - name: "Handle 'open: true' - symlink contents of directory"
      when: item.open | default(false)
      block:
        - name: "Find files and directories in source for 'open: true'"
          ansible.builtin.find:
            paths: "{{ dotfiles_repo_path }}/{{ item.from }}"
            hidden: true
            file_type: any
          register: source_contents

        - name: "Ensure target directory exists for 'open: true'"
          ansible.builtin.file:
            path: "/home/{{ users[0].name }}/{{ item.to | default('.') }}"
            state: directory
            mode: '0755'
          become: true
          become_user: "{{ users[0].name }}"

        - name: "Initialize list for managed files in open:true item"
          set_fact:
            open_true_managed_files: []

        - name: "Include task to manage symlinks for contents of '{{ item.from }}'"
          ansible.builtin.include_tasks: process_charonte_item_open.yml
          loop: "{{ source_contents.files }}"
          loop_control:
            loop_var: sub_item

        - name: "Add open:true item to new repo state"
          set_fact:
            new_repo_state: "{{ new_repo_state +
                                [{'source': item.from, 'path': item.to
                                | default('.'), 'open': true, 'managed_files': open_true_managed_files }] }}"

    # This block handles symlinking the directory itself
    - name: "Handle 'open: false' - symlink directory"
      when: not (item.open | default(false))
      block:
        - name: "Check status of destination path"
          ansible.builtin.stat:
            path: "/home/{{ users[0].name }}/{{ item.to | default(item.from) }}"
          become: true
          become_user: "{{ users[0].name }}"
          register: dest_path_stat

        - name: "Backup existing directory before creating symlink"
          ansible.builtin.command:
            cmd: "mv /home/{{ users[0].name }}/{{ item.to
                                                | default(item.from) }} /home/{{ users[0].name }}/{{ item.to
                                                | default(item.from) }}.bak_{{ ansible_date_time.epoch }}"
          when:
            - dest_path_stat.stat.exists
            # Again, another very weird flag. This means the same as the other one,
            # "if either the destination isnt a link OR the link is pointing to the actual dotfiles_repo_path, then its fine to run"
            - not (dest_path_stat.stat.islnk and dest_path_stat.stat.lnk_target == dotfiles_repo_path + '/' + item.from)
          changed_when: true
          become: true
          become_user: "{{ users[0].name }}"

        - name: "Create dotfile symlink"
          ansible.builtin.file:
            src: "{{ dotfiles_repo_path }}/{{ item.from }}"
            path: "/home/{{ users[0].name }}/{{ item.to | default(item.from) }}"
            state: link
            force: true
          become: true
          become_user: "{{ users[0].name }}"

        - name: "Add open:false item to new repo state"
          set_fact:
            new_repo_state: "{{ new_repo_state + [{'source': item.from, 'path': item.to | default(item.from), 'open': false}] }}"
