- name: Clone {{ aur_helper_item.name }} repo
  ansible.builtin.git:
    repo: "https://aur.archlinux.org/{{ aur_helper_item.name }}.git"
    dest: "/tmp/{{ aur_helper_item.name }}"
    clone: true
    update: true
  become: true
  become_user: "{{ users[0].name }}"
  when: users is defined and users | length > 0

# - name: DEBUG | Quem eu penso que sou?
#   ansible.builtin.debug:
#     msg: "Tentando construir o pacote como o usuário: '{{ users[0].name }}'"
#   when: users is defined and users | length > 0
#

- name: Allow managed user to run pacman without a password
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/11-managed-user-nopasswd-pacman
    line: "{{ users[0].name }} ALL=(ALL) NOPASSWD: /usr/bin/pacman"
    state: present
    create: true
    mode: '0640' # Permissões seguras
    validate: 'visudo -csf %s' # VITAL: Valida o arquivo antes de salvar
  when: users is defined and users | length > 0
  become: true

- name: Build and install {{ aur_helper_item.name }}
  ansible.builtin.command:
    cmd: "makepkg -si --noconfirm"
  args:
    chdir: "/tmp/{{ aur_helper_item.name }}"
    creates: "{{ aur_helper_item.check_file }}"
  become: true
  become_user: "{{ users[0].name }}"
  when: users is defined and users | length > 0

- name: Clean up {{ aur_helper_item.name }} build files
  ansible.builtin.file:
    path: "/tmp/{{ aur_helper_item.name }}"
    state: absent
