- name: Define Hostname
  ansible.builtin.hostname:
    name: "{{ hostname }}"

- name: Load user secrets from file
  ansible.builtin.include_vars:
    file: "{{ secrets.sec_file }}"
    name: user_secrets
  when:
    - secrets is defined
    - secrets.sec_mode is defined
    - secrets.sec_mode == "charonte"
    - secrets.sec_file is defined and secrets.sec_file != ""

- name: Make sure final_users exist
  ansible.builtin.user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    groups: "{{ item.groups | join(',') }}"
    append: true
    create_home: true
    password: "{{ user_secrets[item.name][0].password | default(omit) if user_secrets is defined and user_secrets[item.name] is defined else omit }}"
  loop: "{{ final_users }}"

- name: Manage sudoers
  ansible.builtin.lineinfile:
    path: /etc/sudoers
    regexp: "{{ '^#\\s*%wheel ALL=\\(ALL:ALL\\) ALL' if wheel_access | bool else '^%wheel ALL=\\(ALL:ALL\\) ALL' }}"
    line: "{{ '%wheel ALL=(ALL:ALL) ALL' if wheel_access | bool else '#%wheel ALL=(ALL:ALL) ALL' }}"
    validate: '/usr/sbin/visudo -cf %s'

- name: Check if Ch-aronte destination folder already exists
  ansible.builtin.stat:
    path: "/home/{{ final_users[0].name }}/Ch-aronte"
  register: config_charonte_dest_stat
  when: final_users is defined and final_users | length > 0

- name: "Copy Ch-aronte to first user's home directory"
  ansible.builtin.copy:
    src: "/root/Ch-aronte" # Assumindo que o playbook roda de dentro do chroot
    dest: "/home/{{ final_users[0].name }}/Ch-aronte"
    owner: "{{ final_users[0].name }}"
    group: "{{ final_users[0].name }}"
    mode: '0755'
  when:
    - final_users is defined and final_users | length > 0
    - not config_charonte_dest_stat.exists
