#!/bin/bash
set -e
set -a
source respostas.env
set +a
source scripts/resources.sh

# ==============================================================================
# SETUP DE IDIOMA E VARIÁVEIS
# ==============================================================================
case "$LANGC" in
"Portugues")
  MSG_START="Ok, vamos configurar a região e o idioma do seu sistema."
  MSG_TIMEZONE_INFO="Primeiro, o fuso horário. Você pode ver uma lista com 'timedatectl list-timezones'."
  MSG_TIMEZONE_PROMPT="Digite o seu fuso horário (ex: America/Sao_Paulo): "
  DEFAULT_REGION="America/Sao_Paulo"
  MSG_INVALID_REGION="Fuso horário inválido! O arquivo para essa região não existe em /usr/share/zoneinfo/. Tente novamente."
  MSG_LOCALE_INFO="Agora, vamos configurar o idioma (locale) e o layout do teclado (keymap)."
  MSG_LOCALE_PROMPT="Digite o seu locale principal (ex: pt_BR): "
  DEFAULT_LOCALE="pt_BR"
  MSG_ADD_ANOTHER_LOCALE="Deseja adicionar outro locale para ser gerado pelo sistema? (S/n) "
  MSG_NEXT_LOCALE_PROMPT="Digite o próximo locale (ex: en_US): "
  MSG_KEYMAP_PROMPT="Digite o layout do seu teclado (ex: br-abnt2): "
  DEFAULT_KEYMAP="br-abnt2"
  MSG_CONFIG_SAVED="Configurações de região salvas no seu plugin."
  ;;
"English")
  MSG_START="Alright, let's configure your system's region and language."
  MSG_TIMEZONE_INFO="First, the timezone. You can see a list with 'timedatectl list-timezones'."
  MSG_TIMEZONE_PROMPT="Enter your timezone (e.g., America/New_York): "
  DEFAULT_REGION="America/New_York"
  MSG_INVALID_REGION="Invalid timezone! The file for that region does not exist in /usr/share/zoneinfo/. Please try again."
  MSG_LOCALE_INFO="Now, let's set up the locale and keyboard layout (keymap)."
  MSG_LOCALE_PROMPT="Enter your main locale (e.g., en_US): "
  DEFAULT_LOCALE="en_US"
  MSG_ADD_ANOTHER_LOCALE="Do you want to add another locale to be generated by the system? (Y/n) "
  MSG_NEXT_LOCALE_PROMPT="Enter the next locale (e.g., en_US): "
  MSG_KEYMAP_PROMPT="Enter your keyboard layout (e.g., us): "
  DEFAULT_KEYMAP="us"
  MSG_CONFIG_SAVED="Region settings saved to your plugin."
  ;;
*)
  echo "Unsupported language setting."
  exit 1
  ;;
esac

# ==============================================================================
# FLUXO PRINCIPAL DO SCRIPT
# ==============================================================================

echo "$MSG_START"
echo ""

# --- TIMEZONE ---
echo "$MSG_TIMEZONE_INFO"
read -p "$MSG_TIMEZONE_PROMPT" -r region

if [ -z "$region" ]; then
  region="$DEFAULT_REGION"
fi

# Validação robusta que verifica se o arquivo de fuso horário realmente existe.
while [ ! -f "/usr/share/zoneinfo/$region" ]; do
  echo "$MSG_INVALID_REGION"
  read -p "$MSG_TIMEZONE_PROMPT" -r region
  if [ -z "$region" ]; then
    region="$DEFAULT_REGION" # Garante que o default seja testado se o usuário digitar enter
  fi
done

# --- LOCALE & KEYMAP ---
echo ""
echo "$MSG_LOCALE_INFO"

# Coleta de múltiplos locales
declare -a locales=()
read -p "$MSG_LOCALE_PROMPT" -r main_locale
if [ -z "$main_locale" ]; then
  main_locale="$DEFAULT_LOCALE"
fi
locales+=("$main_locale")

add_another="s"
while [[ "$add_another" != "n" && "$add_another" != "N" ]]; do
  read -p "$MSG_ADD_ANOTHER_LOCALE" -r add_another
  if [[ "$add_another" == "n" || "$add_another" == "N" ]]; then
    break
  fi
  read -p "$MSG_NEXT_LOCALE_PROMPT" -r next_locale
  if [ -n "$next_locale" ]; then
    locales+=("$next_locale")
  fi
done

read -p "$MSG_KEYMAP_PROMPT" -r keymap
if [ -z "$keymap" ]; then
  keymap="$DEFAULT_KEYMAP"
fi

# --- DECLARAR (Salvar no Plugin) ---
yq -iy ".region.timezone = "$region"" "Ch-obolos/$PLUGIN"
yq -iy ".region.keymap = "$keymap"" "Ch-obolos/$PLUGIN"

# Cria a lista de locales no YAML
yq -iy '.region.locale = []' "Ch-obolos/$PLUGIN"
for loc in "${locales[@]}"; do
  yq -iy ".region.locale += ["${loc}.UTF-8"]" "Ch-obolos/$PLUGIN"
done

echo ""
echo "$MSG_CONFIG_SAVED"

# Executa a role do Ansible para aplicar as configurações de região
cp -r ./ /mnt/root/Ch-aronte
arch-chroot /mnt ansible-playbook -vvv /root/Ch-aronte/main.yaml --tags region -e @/root/Ch-aronte/Ch-obolos/"$PLUGIN"
rm -rf /mnt/root/Ch-aronte

sleep 2

