- name: Set timezone
  community.general.timezone:
    name: "{{ region.timezone }}"
  when: region.timezone is defined

- name: Ensure locale is present and uncommented in /etc/locale.gen
  ansible.builtin.lineinfile:
    path: /etc/locale.gen
    regexp: >
      ^{{ '#' | regex_escape() }}\s*({{ region.locale }}\s+UTF-8)
    line: "{{ region.locale }} UTF-8"
    backrefs: yes
  register: locale_gen_change
  when: region.locale is defined

- name: Regenerate locale.gen if it was changed
  ansible.builtin.command:
    cmd: locale-gen
  when: locale_gen_change.changed

- name: Set default system locale
  ansible.builtin.copy:
    content: "LANG={{ region.locale }}\n"
    dest: /etc/locale.conf
    mode: '0644'
  when: region.locale is defined

- name: Set default keyboard layout for virtual console
  ansible.builtin.copy:
    content: "KEYMAP={{ region.keymap }}\n"
    dest: /etc/vconsole.conf
    mode: '0644'
  when: region.keymap is defined
