- name: Set base bootloader
  ansible.builtin.set_fact:
    pkgs_pacotes_firmware_especificos: "{{ ['efibootmgr', 'refind'] if firmware == 'UEFI' else ['grub'] }}"

- name: Unite base pkgs and firmware pkgs
  ansible.builtin.set_fact:
    pkgs_pacotes_base: "{{ (pacotes_base_override | default(necessarios)) | union(pkgs_pacotes_firmware_especificos) }}"

- name: (Debug) Show base pkg list
  ansible.builtin.debug:
    msg: "Firmware detected: {{ firmware }}. base pkg list: {{ pkgs_pacotes_base }}"
  vars:
    firmware: "{{ lookup('env', 'FIRMWARE') }}"

- name: Pkgs list exists
  ansible.builtin.set_fact:
    pkgs_pacotes_desejados: "{{ final_pacotes | default([]) }}"

- name: Unite base pkg and desired pkgs
  ansible.builtin.set_fact:
    pkgs_pacotes_finais: "{{ pkgs_pacotes_base | union(pkgs_pacotes_desejados) }}"

- name: Add bootloader to final package list
  ansible.builtin.set_fact:
    pkgs_pacotes_finais: "{{ pkgs_pacotes_finais | union([bootloader]) }}"
  when: bootloader is defined and bootloader | length > 0


- name: Get true pkg list
  ansible.builtin.command:
    cmd: pacman -Qqe
  register: pkgs_pacotes_instalados_raw
  changed_when: false
  check_mode: false

- name: Get removal pkgs
  ansible.builtin.set_fact:
    pkgs_pacotes_a_remover: "{{ pkgs_pacotes_instalados_raw.stdout_lines | difference(pkgs_pacotes_finais) }}"

- name: (Debug) Show removal pkgs
  ansible.builtin.debug:
    var: pkgs_pacotes_a_remover
  when: pkgs_pacotes_a_remover | length > 0

- name: Confirm removal pkgs
  ansible.builtin.pause:
    prompt: |
      WARNING: Ch-aronte WILL REMOVE these last {{ pkgs_pacotes_a_remover | length }} packages.

      This action CANNOT be undone (unless you reinstall everything).
      Do you want to follow through? (Type 'yes' or 'sim' to continue.):
  when: pkgs_pacotes_a_remover | length > 0
  register: pause_result
  failed_when: "'sim' not in pause_result.user_input or 'yes' not in pause_result.user_input"

- name: Remove removal pkgs
  community.general.pacman:
    name: "{{ pkgs_pacotes_a_remover }}"
    state: absent
  become: true
  when: pkgs_pacotes_a_remover | length > 0

- name: Install wanted pkgs
  community.general.pacman:
    name: "{{ pkgs_pacotes_finais }}"
    state: present
  become: true
  when: pkgs_pacotes_desejados | length > 0
