- name: "Manage normal service: {{ service_item.name }}"
  when: not (service_item.dense_service | default(false))
  ansible.builtin.service:
    name: "{{ service_item.name }}"
    state: "{{ service_item.state | default('started') }}"
    enabled: "{{ service_item.enabled | default(true) }}"
  become: true

- name: "Manage dense service: {{ service_item.name }}"
  when: service_item.dense_service | default(false)
  block:
    - name: "Find services matching regex for {{ service_item.name }}"
      ansible.builtin.set_fact:
        matched_services: "{{ all_system_services | select('match', '^(' + service_item.name + ')(\\.service)?$') | list }}"
    - name: "Apply state to matched services for {{ service_item.name }}"
      ansible.builtin.service:
        name: "{{ item }}"
        state: "{{ service_item.state | default('started') }}"
        enabled: "{{ service_item.enabled | default(true) }}"
      loop: "{{ matched_services }}"
      become: true
